version: "1"
services:
  dev:
    build: .
    image: lockfox-pico-sdk
    container_name: lockfox-pico-sdk
    tty: true
    volumes:
      - ./luckfox-pico:/root/luckfox-pico
    working_dir: /root/luckfox-pico/project
    entrypoint: ["/bin/bash"]
    command: []