version: "1"
services:
  dev:
    build:
      dockerfile: Dockerfile
    image: lockfox-pico-sdk
    container_name: lockfox-pico-sdk
    tty: true
    volumes:
      - ./luckfox-pico:/root/luckfox-pico
    env_file: environments
    working_dir: /root/luckfox-pico
    entrypoint: ["/bin/bash"]